name: Kotlin CI

on: [push]  # İş akışını push olaylarında tetikle

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Compile and Run Kotlin code
        run: |
          kotlinc PatikaÖdev1.kt -include-runtime -d PatikaÖdev1.jar
          java -jar main.jar
